services:

  backend:
    build: ./Backend
    container_name: django_app 
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./Frontend
    container_name: react_app
    volumes:
      - ./Frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
